# Generated by Django 2.0.4 on 2018-06-02 13:25

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=64)),
                ('descricao', models.TextField()),
                ('anoinicio', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2018)])),
                ('anofim', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2018)])),
                ('instituicao', models.TextField()),
                ('cidade', models.TextField()),
                ('nacao', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_experiencia', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.SmallIntegerField(choices=[(1, 'CPF'), (2, 'CNPJ')])),
                ('foto', models.ImageField(blank=True, upload_to='thumbpath')),
                ('descricao', models.TextField(blank=True)),
                ('mainfunction', models.TextField()),
                ('organisationalskills', models.SmallIntegerField(blank=True, default=0)),
                ('communicationalskills', models.SmallIntegerField(blank=True, default=0)),
                ('projectmanagmentskills', models.SmallIntegerField(blank=True, default=0)),
                ('userInstance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinstance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('sexo', models.SmallIntegerField(choices=[(1, 'FEMININO'), (2, 'MASCULINO'), (3, 'NÃO DECLARAR')])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoaf', to='pmanager.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('ramo', models.CharField(max_length=64)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dadospj', to='pmanager.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=9)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('descricao', models.TextField()),
                ('prerequisitos', models.TextField()),
                ('fk_pjuridica', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='pmanager.PJuridica')),
            ],
        ),
    ]
