# Generated by Django 2.0.4 on 2018-04-26 16:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.SmallIntegerField(choices=[(1, 'pessoafisica'), (2, 'pessoajuridica')])),
                ('foto', models.ImageField(blank=True, upload_to='thumbpath')),
                ('userInstance', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userinstance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('sexo', models.SmallIntegerField(choices=[(1, 'FEMININO'), (2, 'MASCULINO'), (3, 'NÃO DECLARAR')])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoaf', to='pmanager.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='PessoaProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('ramo', models.CharField(max_length=64)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dadospj', to='pmanager.Pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=64)),
                ('descricao', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(1, 'EXECUTANTO'), (2, 'FINALIZADO'), (3, 'PAUSADO'), (4, 'INTERRONPIDO')])),
                ('datainicio', models.DateField()),
                ('datafim', models.DateField()),
                ('tipo', models.SmallIntegerField(choices=[(1, 'PROJETO'), (2, 'EMPREGO'), (3, 'FACULDADE'), (4, 'TRABALHO PESSOAL')])),
                ('instituicao', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=9)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fone', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('descricao', models.TextField()),
                ('prerequisitos', models.TextField()),
                ('fk_pjuridica', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='pmanager.PJuridica')),
            ],
        ),
        migrations.AddField(
            model_name='pessoaprojeto',
            name='fk_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_projeto', to='pmanager.Projeto'),
        ),
        migrations.AddField(
            model_name='pessoaprojeto',
            name='fk_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
