# Generated by Django 2.0.4 on 2018-04-19 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pmanager.cpfValidation
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Foto',
            fields=[
                ('nome', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='thumbpath')),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('sexo', models.SmallIntegerField(choices=[(1, 'FEMININO'), (2, 'MASCULINO'), (3, 'NÃO DECLARAR')])),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pessoaf', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PessoaProjeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='PJuridica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, upload_to='thumbpath')),
                ('cnpj', models.CharField(max_length=14, unique=True, validators=[pmanager.cpfValidation.validate_CNPJ])),
                ('ramo', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id_projeto', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(blank=True, max_length=64)),
                ('descricao', models.TextField()),
                ('status', models.SmallIntegerField(choices=[(1, 'EXECUTANTO'), (2, 'FINALIZADO'), (3, 'PAUSADO'), (4, 'INTERRONPIDO')])),
                ('datainicio', models.DateField()),
                ('datafim', models.DateField()),
                ('tipo', models.SmallIntegerField(choices=[(1, 'PROJETO'), (2, 'EMPREGO'), (3, 'FACULDADE'), (4, 'TRABALHO PESSOAL')])),
                ('instituicao', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TelefonePF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=9)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fone', to='pmanager.PessoaFisica')),
            ],
        ),
        migrations.CreateModel(
            name='TelefonePJ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=9)),
                ('pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fone', to='pmanager.PJuridica')),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('descricao', models.TextField()),
                ('prerequisitos', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PessoaFisicaProjeto',
            fields=[
                ('pessoaprojeto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pmanager.PessoaProjeto')),
                ('fk_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pfusuario', to='pmanager.PessoaFisica')),
            ],
            bases=('pmanager.pessoaprojeto',),
        ),
        migrations.CreateModel(
            name='PJuridicaProjeto',
            fields=[
                ('pessoaprojeto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pmanager.PessoaProjeto')),
            ],
            bases=('pmanager.pessoaprojeto',),
        ),
        migrations.AddField(
            model_name='pjuridica',
            name='fk_vaga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='pmanager.Vaga'),
        ),
        migrations.AddField(
            model_name='pjuridica',
            name='usuario',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dadospj', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pessoaprojeto',
            name='fk_projeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projeto', to='pmanager.Projeto'),
        ),
        migrations.AddField(
            model_name='pjuridicaprojeto',
            name='fk_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_pjusuario', to='pmanager.PJuridica'),
        ),
    ]
