# Generated by Django 2.0.4 on 2018-04-26 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='usertype',
            field=models.SmallIntegerField(choices=[(1, 'CPF'), (2, 'CNPJ')]),
        ),
    ]
