# Generated by Django 2.0.4 on 2018-05-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='communicationalskills',
            field=models.SmallIntegerField(blank=True, default=60),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='mainfunction',
            field=models.TextField(default=54),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='organisationalskills',
            field=models.SmallIntegerField(blank=True, default=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pessoa',
            name='projectmanagmentskills',
            field=models.SmallIntegerField(blank=True, default=40),
            preserve_default=False,
        ),
    ]
