# Generated by Django 2.0.4 on 2018-06-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='descricao',
            field=models.CharField(max_length=256),
        ),
    ]
