# Generated by Django 2.0.4 on 2018-04-20 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pmanager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foto',
            name='path',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='pjuridica',
            name='cnpj',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='pjuridica',
            name='fk_vaga',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='pmanager.Vaga'),
        ),
    ]
