# Generated by Django 2.0.4 on 2018-04-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmanager', '0002_auto_20180426_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
