# Generated by Django 2.0.4 on 2018-06-02 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmanager', '0002_auto_20180602_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='cidade',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='instituicao',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='nacao',
            field=models.CharField(max_length=256),
        ),
    ]
