# Generated by Django 2.0.4 on 2018-06-04 16:41

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pmanager', '0003_auto_20180602_1820'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursename', models.CharField(blank=True, max_length=64)),
                ('anoinicio', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2018)])),
                ('anofim', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(2018)])),
                ('instituicao', models.CharField(max_length=512)),
                ('cidade', models.CharField(max_length=512)),
                ('nacao', models.CharField(max_length=256)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_education', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
