# Generated by Django 2.0.4 on 2018-06-04 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pmanager', '0005_auto_20180604_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ddd', models.CharField(max_length=2)),
                ('numero', models.CharField(max_length=9)),
                ('email', models.EmailField(max_length=254)),
                ('userct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contato', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='telefone',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='Telefone',
        ),
    ]
