# Generated by Django 2.0.4 on 2018-06-04 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmanager', '0006_auto_20180604_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='ddd',
            field=models.CharField(max_length=3),
        ),
    ]
