# Generated by Django 2.0.4 on 2018-06-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmanager', '0007_auto_20180604_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contato',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(default='static/img/img-profile.jpg', upload_to='media/'),
        ),
    ]
