# Generated by Django 2.0.4 on 2018-06-05 20:38

from django.db import migrations, models
import pmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('pmanager', '0008_auto_20180605_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(default='static/img/img-profile.jpg', upload_to=pmanager.models.upload_to),
        ),
    ]
