# Generated by Django 2.0.4 on 2018-06-05 21:31

from django.db import migrations, models
import pmanager.models


class Migration(migrations.Migration):

    dependencies = [
        ('pmanager', '0009_auto_20180605_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='foto',
            field=models.ImageField(default='pmanager/img-profile.jpg', upload_to=pmanager.models.upload_to),
        ),
    ]
